AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to create S3 buckets for server access logs and inventory reports'

Resources:
  ServerAccessLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['sal-', !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]]]

  InventoryReportsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['inventory-', !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]]]

  GlueJobBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: !Join ['', ['glue-job-', !Select [0, !Split ['-', !Select [2, !Split ['/', !Ref 'AWS::StackId']]]]]]

  GlueJobRole: 
    Type: "AWS::IAM::Role"
    Properties: 
      RoleName: "AWSGlueServiceRoleDefault"
      AssumeRolePolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Principal: 
              Service: 
                - "glue.amazonaws.com"
            Action: 
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole


Outputs:
  ServerAccessLogsBucketName:
    Value: !Ref ServerAccessLogsBucket
    Description: 'S3 Bucket for storing server access logs'

  InventoryReportsBucketName:
    Value: !Ref InventoryReportsBucket
    Description: 'S3 Bucket for storing inventory reports'

  GlueJobBucketBucketName:
    Value: !Ref GlueJobBucket
    Description: 'S3 Bucket for storing inventory reports'
